{% set name = "instaloader" %}
{% set version = "4.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/instaloader-{{ version }}.tar.gz
  sha256: 902cc8b9569ca7437323199c8e55dbdcd15ea5c8e874c7864e84a36dd55f8584

build:
  entry_points:
    - instaloader=instaloader.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - requests >=2.4

test:
  imports:
    - instaloader
  commands:
    - pip check
    - instaloader --help
  requires:
    - pip

about:
  home: https://instaloader.github.io/
  summary: Download pictures (or videos) along with their captions and other metadata from Instagram.
  license: MIT
  license_file: LICENSE
  doc_url: https://instaloader.github.io/index.html
  dev_url: https://github.com/instaloader/instaloader

extra:
  recipe-maintainers:
    - fsktom
